### ISSUE TITLE
Error pg-connection-string testing 

### ISSUE THREAD

**Issue by rbonazzo** [calebmer/postgraphql#29]
Hi Calebmer
after following the instructions in https://github.com/calebmer/postgraphql/tree/master/examples/forum

postgraphql postgres://localhost:5432 --schema forum_example --development 
doesn't work with or without user:password 
Error is:

module.js:327
    throw err;
    ^

Error: Cannot find module 'pg-connection-string'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/postgraphql/dist/main.js:18:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

Regards
rbonazzo

**Comment by calebmer** [comment]
What version of npm are you on?

**Comment by rbonazzo** [comment]
npm@2.14.12

**Comment by calebmer** [comment]
npm version 3 hid this error for me, `pg-connection-string` is a dependency of `pg` and because of npm 3's flat dependency installation `postgraphql` could access it. Totally missed that it wasn't in `package.json`. Thanks for reporting, this is fixed in version `1.1.5` 😊

**Comment by rbonazzo** [comment]
so I have to use npm 3?

**Comment by calebmer** [comment]
Nope, version `1.1.5` fixes this error for all versions of npm.

**Comment by rbonazzo** [comment]
I now it's seem stupid 
but I still have the same problem 
delete all, then again git clone and so on 
and still not working
can you please help me?
Thx
Rinaldo

**Comment by calebmer** [comment]
What version of `postgraphql`? And could I see the output of `npm ls postgraphql` (add a `-g` flag if you installed it globally).

**Comment by rbonazzo** [comment]
Hi 
solved, workaround
uninstall postgraphql, pg
reinstall all 
It's work
Thank's for you help 

Regards
Rinaldo

**Comment by calebmer** [comment]
Awesome, great to see it working 😊🎉
